# Generated by Django 3.1.7 on 2021-03-27 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('po_batkovi', models.CharField(max_length=50, verbose_name='По-батькові')),
                ('photo', models.ImageField(upload_to='employees_photo', verbose_name='Фотографія')),
                ('about', models.TextField(verbose_name='Про співробітника')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeestype', verbose_name='Тип ')),
            ],
            options={
                'verbose_name': 'Співробітника',
                'verbose_name_plural': 'Співробітники',
            },
        ),
    ]
