# Generated by Django 3.1.7 on 2021-03-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employees_employeestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('koshtorys', models.FileField(upload_to='files', verbose_name='Кошторис')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Деражавне забезпечення',
                'verbose_name_plural': 'Деражавне забезпечення',
            },
        ),
        migrations.CreateModel(
            name='FinanceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financ_zvit', models.FileField(upload_to='files', verbose_name='PDF-файл')),
                ('Finance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.finance')),
            ],
        ),
    ]
