# Generated by Django 3.1.7 on 2021-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210412_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', unique=True)),
                ('post', models.TextField(verbose_name='Текст поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Протидія булінгу',
            },
        ),
        migrations.CreateModel(
            name='DistanceStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('post', models.TextField(verbose_name='Текст поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Дистанційне навчання',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=200, verbose_name='Вакансія')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
            },
        ),
        migrations.AlterField(
            model_name='finance',
            name='koshtorys',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Кошторис'),
        ),
    ]
