# Generated by Django 3.1.7 on 2021-05-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210508_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.CharField(default=1, max_length=150, verbose_name='Посада'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpsychologa',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeestype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Зображення'),
        ),
    ]
