# Generated by Django 3.1.7 on 2022-04-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220418_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва вкладки')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sitetab', verbose_name='Вкладка на якій буде знаходитися документ'),
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
