# Generated by Django 3.1.7 on 2022-04-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220426_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitetab',
            options={'verbose_name': 'Вкладка', 'verbose_name_plural': 'Вкладки'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='type',
            new_name='tab',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва документа(-ів)'),
        ),
    ]
