# Generated by Django 3.1.7 on 2022-04-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220426_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='tab',
            field=models.ForeignKey(default='Документи', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sitetab', verbose_name='Вкладка на якій буде знаходитися документ'),
        ),
    ]
