# Generated by Django 3.1.7 on 2022-04-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220426_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.AddField(
            model_name='employees',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(default='Вчитель', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.employeestype', verbose_name='Тип'),
        ),
    ]
