# Generated by Django 3.1.7 on 2022-04-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220426_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='order',
        ),
    ]
