# Generated by Django 3.1.7 on 2022-04-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_employees_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='order',
        ),
    ]
