# Generated by Django 3.1.7 on 2022-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_employees_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('order',), 'verbose_name': 'Співробітника', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
