# Generated by Django 3.1.7 on 2022-04-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220426_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.employeestype', verbose_name='Розділ'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy',
            field=models.TextField(max_length=200, verbose_name='Вакансія'),
        ),
    ]
