# Generated by Django 3.1.7 on 2022-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220502_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField()),
                ('document', models.FileField(upload_to='files', verbose_name='PDF-файл')),
            ],
        ),
    ]
