# Generated by Django 3.1.7 on 2022-05-02 15:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_enterschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterschool',
            name='page',
        ),
        migrations.AddField(
            model_name='enterschool',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
