# Generated by Django 3.1.7 on 2022-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220502_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterschool',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='PDF-файл'),
        ),
    ]
