# Generated by Django 3.1.7 on 2022-05-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220502_1057'),
        ('main', '0027_auto_20220502_1913'),
    ]

    operations = [
    ]
