# Generated by Django 3.1.7 on 2022-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20220504_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('document', models.FileField(blank=True, null=True, upload_to='files', verbose_name='PDF-файл')),
            ],
            options={
                'verbose_name': 'Розклад дистанційних уроків',
                'verbose_name_plural': 'Розклади дистанційних уроків',
                'ordering': ('order',),
            },
        ),
    ]
