# Generated by Django 3.1.7 on 2022-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_distancelessons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancelessons',
            options={'verbose_name': 'Розклад дистанційних уроків', 'verbose_name_plural': 'Розклади дистанційних уроків'},
        ),
        migrations.AddField(
            model_name='distancelessons',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Назва'),
            preserve_default=False,
        ),
    ]
