# Generated by Django 3.1.7 on 2022-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220504_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancelessons',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
