# Generated by Django 3.1.7 on 2024-01-31 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220506_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tab',
            field=models.ForeignKey(default='Документи', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sitetab', verbose_name='Вкладинка на якій буде знаходитися документ(-и)'),
        ),
        migrations.CreateModel(
            name='NavTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('tab_num', models.IntegerField(blank=True, default=None, null=True)),
                ('is_page', models.BooleanField(default=True)),
                ('relation_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('related_tab_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.navtab')),
            ],
        ),
    ]
