# Generated by Django 3.1.7 on 2024-02-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20240131_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtab',
            name='relation_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
